# Default values for inferno.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kolockuloc/inferno
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  nodePort: 30080

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /workers
    port: http

readinessProbe:
  httpGet:
    path: /workers
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80